### ISSUE TITLE
Lag after boot with new SMBIOS (MacMini7,1)

### ISSUE THREAD

**Issue by Bresjee99** [zearp/OptiHack#50] opened 2021-07-07 19:13 UTC
I recently converted my Optiplex 9020 to the newest release with SMBIOS MacMini7,1 to be more compatible with Monterey. But the first 10 to 15 seconds after a fresh boot, the system is really laggy in Big Sur. I reverted my EFI to the SMBIOS iMac15,1 version and the lag immediately disappeared. 

I'm using a 4790 with igpu only, combined with 24gb of ram and Samsung EVO 860 SSD.

**Comment by zearp** [comment] 2021-07-07 19:40
I'm not experiencing this but I do experience some lag with usb keyboard/mice sporadically. I tried to pin that down but it happens too rarely without any changes so I've just thrown that on the interference pile. I have the exact same on my MacBook where the first 10 seconds after booting things are super laggy and from time to time any bluetooth connection also gets very laggy. I think it's something in macOS causing that since it happens on my MacBook too.

As for your lag, you'd have to some digging in the logs to see what differs when you change them. Did you also change the model in USBPorts.kext? A mismatch between model used in there and config might cause it, but I'm not sure. Logs will tell you. I would save boot logs for both SMBIOS and compare them. There are time stamps to spot differences more easily. I would also be curious to know if this happens if you do a clean install, and then once tested in a clean install import all the stuff from a backup and see it it happens again.

A test like that would tell us a lot. If a clean install + new clean user doesn't have the issue using the Mac mini SMBIOS we have a good baseline. Then importing all your stuff with the migration tool and try again. If it lag comes back we know it's something software, maybe some app doesn't like the SMBIOS change. I had many apps cause a big load cuz they decided to verify themselves after I changed it. Something like that could be happening. If the lag doesn't;t come back then I wouldn't know what would be the cause, but sometimes a clean install just fixes weird issues even after importing all your stuff again.

If you can reproduce this issue with a clean install + new user then also let me know so I can try it here too. Other than the sporadic usb device lag I have not noticed anything odd. To help me help you best I would need logs and steps to reproduce, ideally on a clean system but I know not everybody has spare ssd laying around to do clean installs on. But it is the best way to sort things out cuz I don't know what people do and install and change on their systems. So despite the h/w being exactly the same many issues can arise form software doing who knows what on start-up and I can't even blame apps for doing weird things when the platform they were installed on significantly changes from their perspective. Lots of registered apps will also lose their activation and such.

It would also be interesting the reverse of what you experience, clean install Big Sur with the Mac mini SMBIOS and then change it back and see what happens. But that would take a lot of time re-installing your apps instead of using a backup. No matter what these kind of things are always time consuming to solve but with some time and log reading/comparing and some reinstalls it is at least possible to pin down what's happening by trial/error/deduction. Oh, have you tried beta 1 or beta 2 of Monterey and experience the same issue there?

Lots of stuff to read, can't really sum it up any better.

Good luck!

**Comment by zearp** [comment] 2021-07-08 00:46
You might be onto something. This usb lag is really weird. I did a bunch of reboots and it happens about 7 out of 10 times but not always at the same points. The boor process is always the same due to FileVault, it makes you login very early in the boot process once thats done it still has to do 80% of the kernel/os loading. Moving the mouse makes it very apparent when it's lagging or not. It's not the whole system that is lagging either, just the usb inputs and only for a short amount of time. Anywhere from 5 to 30 seconds here.

The laggy movements are really weird though. When I enter my password early boot the mouse movements are fine. When its loading start-up apps its fine then laggy then fine then laggy. I wish it was more predicable, happening around the same times but it doesn't. I didn't try swapping SMBIOS just yet. Want to see if things can be sorted by other means. I've tried moving the usb map to a slightly better wat of setting it up. I think that fixed the iDevice issue where it sometimes gets stuck in a connect/disconnect loop. But the laggy mouse is still there.

More research and testing is needed. Good find though!

I blame things rather fast on my crappy RF conditions here. Got a lot of interference messing with bluetooth and wifi and also wireless usb dongles I use. There are some large mobile relays/repeaters here own the roof and I don't think they're shielded properly. I need a large faraday cage lol.

**Comment by zearp** [comment] 2021-07-08 01:11
Disregard anything I wrote in here earlier. I think I found the culprit but it will require some testing to see if the solution can be easy or has to involve some extra configuration steps depending on which SMBIOS is used. I hope the former can be done.

**Comment by Bresjee99** [comment] 2021-07-08 09:05
Thanks for diving in immediately. I've read your earlier posts in the mail.

If something needs to be tested, I'm here to help! I can swap my SSD's anytime 

I've already did some testing with a spare SSD and a clean install. If I swap the EFIs between MacMini7,1 and iMac15,1 I can trigger the lag by that. (all on Big Sur 11.2.1, freshly installed)

**Comment by zearp** [comment] 2021-07-08 12:56
What we experience is not lag but perceived as lag. What's happening is that there are frames being skipped (not rendered). Easy to spot when moving the mouse steadily. The mouse moves but you don't always see it move cuz its skipping caused by macOS trying to setup or do something (see log below) with the frame buffer. Once thats done everything is normal. You can tell it skips frames cuz the mouse is moving normally, you just don't see every frame where it moves. The logs show about 150 entries of these before the lag is gone:

```
kernel: (AppleIntelFramebufferAzul) [DPCD_Info] Port = 0x64200, AuxPort=0xe4210
kernel: (AppleIntelFramebufferAzul) [DPCD_Info] Aux read failed for kDPCD_REV return 0xe00002d6
kernel: (AppleIntelFramebufferAzul) [DPCD_Info] Port = 0x64100, AuxPort=0xe4110
kernel: (AppleIntelFramebufferAzul) [DPCD_Info] SetDPPowerState failed return 0xe00002bc
```

This is caused by the frame buffer config and is also where it can get tricky due to the many options we have from this point. Removing the complete frame buffer section from the config file fixes the lag. You can try this out yourself, everything will work fine as long as the screen(s) is/are connected before booting up. Any hot plug event wil cause a panic/reboot. Which is expected without any configuration. The HD4600 is natively supported and doesn't require any device-id spoofing. We get full acceleration with nothing configured. This is sort of my baseline. I can dual screen (extend and mirror) and there is no lag when starting up. The platform-id its using in this config is the same we use now. As soon as I add the platform-id and enable WhateverGreen patching the lag returns.

The fix is simple yet tricky. We have to re-do the frame buffer config and setup everything properly. The thing thats making it a bit tricky is that different platform-id's have different port layouts and seem to interact differently with different SMBIOS. Which explains why iMac 15,1 has no lag but Mac mini 7,1 does, despite them both using the same platform-id. The platform-id we currently use (0x0D220003) looks like this:

```
D: 0D220003, STOLEN: 32 MB, FBMEM: 19 MB, VRAM: 1536 MB, Flags: 0x00000402
TOTAL STOLEN: 52 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 116 MB, MAX OVERALL: 117 MB (123219968 bytes)
Camellia: CamelliaDisabled (0), Freq: 5273 Hz, FreqMax: 5273 Hz
Mobile: 0, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[1] busId: 0x05, pipe: 9, type: 0x00000400, flags: 0x00000087 - ConnectorDP
[2] busId: 0x04, pipe: 10, type: 0x00000400, flags: 0x00000087 - ConnectorDP
[3] busId: 0x06, pipe: 8, type: 0x00000400, flags: 0x00000011 - ConnectorDP
01050900 00040000 87000000
02040A00 00040000 87000000
03060800 00040000 11000000
```
It has 3 connectors, which are all set to DP and have their own pipe and bus-id values. These do not always match with the actual hardware used. Our machines also have 3 connectors, 2x DP and 1x VGA. In theory the only thing needed to do is setup these connectors properly. This has proven more difficult that it should be. This is mainly on me cuz I spend a lot of time on this when I started out and didn't fully understand which might have clouded me on this part. It's weird cuz compared to all the other stuff this part should be pretty straight forward. Time consuming yes, trying out the stuff takes a lot of reboots but it's not intensive work. But somehow I always end up with some parts not working and they should.

The fix might as simple as someone going over the guides and try to setup the frame buffer from scratch. Having 2 screens, ideally 3 one with VGA would be perfect. I have that but I think I need fresh eyes cuz I might have developed a blind spot somehow somewhere. I won't say it's annoying cuz I only put in time when I want and can but it sure is eluding me.

I'd love to get thing to work with the current platform-id but it might be needed to use another. There are 14 desktop platform-ids with connectors. Some have 2 some have 3 and some even have 4. I'm not counting the ones with no connectors as thats just headless. Each of these platform-ids has their own settings block as I put above. This opens so many options it would take several hours trying them. So I rather focus on what we use now and try to make that work first. If only to limit the sheer number of things of try.

I did a lot of this exact stuff a while ago, together with @mgrimace we did a lot of messing about and testing. Not all info in there might be accurate but it might be an interesting thing for you to skim over: https://github.com/zearp/OptiHack/pull/33

There are also a lot of guides/etc on how-to patch things properly and they all do it in their own way and some of those might be outdated by now, but I'll include them anyways. Specially the thread on OSXLatitude has a lot of good info but the method they use we no longer use; patching system kexts directly. The principles and information is still very valuable.

Sources:
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-hd-graphics-4200-5200-haswell-processors
https://osxlatitude.com/forums/topic/10267-understanding-and-patching-framebuffer-haswell/

There's a lot to take it and I appreciate you want to help out, do what you feel like doing and is fun/educational. A tl;dr of this all would be; try making a frame buffer/connectors/etc config from scratch for our machines cuz I might have a blind spot after messing about with this too much. Maybe the fix is to not configure anything and never hot-plug a screen haha.

**Comment by zearp** [comment] 2021-07-08 13:02
The error itself seems to suggest some power management things is going wrong and it retries a bunch of times before giving up. Maybe this can be fixed with flags, but those are very sparsely documented and a bit of a black hole. I guess the Mac mini SMBIOS has different power management than the iMac one. DisplayPort power management settings/flags are completely new to me. I'll look into that and see what's it about. I do believe that once we have a proper frame buffer config everything will be fine forever. I just can't get a full config it right, with all the bus-id and connectors setup properly it should work and keep working as it's just a hardware profile in way. It doesn't change anymore like our usb map.

**Comment by zearp** [comment] 2021-07-08 16:43
Some small updates after running some tests and a bunch of reboots. I did my testing on Monterey might try some on Big Sur later but my focus is on getting ready for Monterey which will be out in a few months.

Dual screen: does not work properly at all using the Mac mini SMBIOS. It's either glitchy or crashes/panics. Some settings result in two black screens but remote desktop works fine. With others the boot just stalls. I've cycled trough all the bus-ids but nothing would give me fully working dual screens. Not sure what is needed to get this work on the Mac mini SMBIOS. It shouldn't be impossible though.

Single screen: all is fine and getting rid of the lag was relatively easy; disable the frame buffer on con0 (vga) and the lag is gone. I added all 3 connectors to the config and hopefully set them up correctly. Both DisplayPorts work too, just not at the same time for now. Audio over both also works, so it doesn't matter which of the DisplayPorts we use. With previous frame buffer configs audio would only work on one of the ports. I think that was fixed by using the same flags for both connectors.

I'll post my test frame buffer below.

**Comment by zearp** [comment] 2021-07-08 16:59
![fb](https://user-images.githubusercontent.com/63272687/124961278-8bdb2380-e01d-11eb-8cc3-e0ccdaa047e4.png)

The fixes only apply to some edge cases, like some brands of screen don't turn back on after wake unless force-online is enabled. I tried with and without those fixes and they don't seem to do any harm. Dual screen problems remain even with the fixes removed.

The fbmem and stolenmem options might not be needed as well, but I think it did fix some 4k related things and also matches the dvmd-pre allocation to the 64mb we changed it to. It also doesn't seem to hurt anything. 

```
                        <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
                        <dict>
                                <key>AAPL,ig-platform-id</key>
                                <data>AwAiDQ==</data>
                                <key>disable-external-gpu</key>
                                <data>AQAAAA==</data>
                                <key>disable-hdmi-patches</key>
                                <data>AQAAAA==</data>
                                <key>enable-hdmi20</key>
                                <data>AAAAAA==</data>
                                <key>enable-max-pixel-clock-override</key>
                                <data>AQAAAA==</data>
                                <key>force-online</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-con0-enable</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-con0-alldata</key>
                                <data>AQAJAAEAAAARAAAA</data>
                                <key>framebuffer-con1-enable</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-con1-alldata</key>
                                <data>AgQKAAAEAACHAAAA</data>
                                <key>framebuffer-con2-enable</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-con2-alldata</key>
                                <data>AwYIAAAEAACHAAAA</data>
                                <key>framebuffer-fbmem</key>
                                <data>AAAAAw==</data>
                                <key>framebuffer-patch-enable</key>
                                <data>AQAAAA==</data>
                                <key>framebuffer-stolenmem</key>
                                <data>AAAABA==</data>
                                <key>hda-gfx</key>
                                <string>onboard-1</string>
                        </dict>
```

I don't know how to fix dual screen on the Mac mini SMBIOS but it must be possible. I'll test dual screen on Big Sur and the two iMac SMBIOS with the frame buffer above as well. Hopefully sometime this week. At leats the cause of the lag was found and fixed. Dual screens is something for another day to try and fix. It could even be a bug or a change in Monterey breaking dual screens and may need a WhateverGreen update or something else. Time will tell.

Let me know if disabling con0 fixes it for you too!

**Comment by zearp** [comment] 2021-07-08 17:07
Added the connectors to the repo's config too: https://github.com/zearp/OptiHack/commit/03df443dd58acfa12e2b83d548ca7758f443619d

**Comment by zearp** [comment] 2021-07-11 20:56
Closing as it has been resolved and the while trouble making frame buffer has been removed here: https://github.com/zearp/OptiHack/commit/486d7d91b7b4826bc68ad8bebcdd52a2095bde94

This might also sort out other (weird) issues that were caused by that frame buffer being active.

**Comment by zearp** [comment] 2021-07-11 20:57
Closing as it has been resolved and the trouble making frame buffer has been removed here: https://github.com/zearp/OptiHack/commit/486d7d91b7b4826bc68ad8bebcdd52a2095bde94

This might also sort out other (weird) issues that were caused by that frame buffer being active.

**Closed as completed by zearp** 2021-07-11 20:56 UTC
