### ISSUE TITLE
Poweroff but reboot then

### ISSUE THREAD

**Issue by MrSome1** [zearp/OptiHack#62] opened 2021-08-15 06:17 UTC
Hi there, I just install Mojave 10.14.6 (Build 18G103) on my Optilex 7020 with an i5-4590 CPU and no DGPU, following your wonderful installation guide. iMac15,1 was the choice, and it could boot into the OSX.
The problem is, when I shutdown the computer, it cuts off the power, but then reboot. I have tried to reinstall and follow every steps in the guide, for at least 3 times, and I also tried to generate SSDT-PLUG and SSDT-EC from my original DSDT, but the problem is still there. But when boot into the OSX base system with the installer USB device, it will shutdown normally. Any idea about this?
By the way, I'm a coder, I can do something just with the key point of the problem.
Well, it's a really great installation guide of yours, really thanks for that

**Comment by zearp** [comment] 2021-08-15 11:52
I can’t reproduce this on mine with Catalina, Big Sur or Monterey.

Either you forgot some step or Mojave needs additional fixes. 

The only way for me to reproduce is to install Mojave too. I won’t have time for that anytime soon. 

Does it happen with any of the OS versions I mentioned?

**Comment by MrSome1** [comment] 2021-08-15 13:43
Thanks for the reply, no need to install Mojave for you, time is treasure.
I will try one of the three OS versions you mentioned, thanks again.



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 15, 2021 19:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zearp/OptiHack] Poweroff but reboot then (#62)




 
I can’t reproduce this on mine with Catalina, Big Sur or Monterey.
 
Either you forgot some step or Mojave needs additional fixes.
 
The only way for me to reproduce is to install Mojave too. I won’t have time for that anytime soon.
 
Does it happen with any of the OS versions I mentioned?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zearp** [comment] 2021-08-15 14:11
No worries, I like to tinker just didn't have any disks ready or time but things can change fast around here. Found an old 30gb ssd I forgot about and grabbed the latest installer, which is still from 2019, I guess the 2021 security update released last month for it isn't integrated in the installer.

Forgot how fast older macOS installs when they don't need to seal the entire filesystem. Installed using current EFI and iMac15,1 in about 15 minutes. Shutting down just shuts the machine down normally. I can see a ```CPU Halted``` message pass by as one of the latest message before it turns off and remains off.

What do you see on yours? It is pretty weird it turns back on cuz macOS just sends a power down message the same way Linux or Windows would do. It turning on again can have some caused like bios or ACPI but if you have the latest bios and use the default ACPI patches it should work.

My best guess would be that ```AC Recovery``` in the bios has been enabled or set to last instead of disabled. If you landed bios defaults before making changes that should be off. Can't think fo anything else what would cause the system to turn back on after sending a shutdown to it.

**Comment by zearp** [comment] 2021-08-15 14:17
I'll apply the latest updates to it and see if that breaks anything. If it doesn't then I don't know what else I can try to reproduce. There were 2 macOS updates and one Safari update on my clean install of 10.14.6 -- shouldn't take too long to install those. I'll update here again once its done.

**Comment by zearp** [comment] 2021-08-15 14:18
No worries, I like to tinker just didn't have any disks ready or time but things can change fast around here. Found an old 30gb ssd I forgot about and grabbed the latest installer, which is still from 2019, I guess the 2021 security update released last month for it isn't integrated in the installer.

Forgot how fast older macOS installs when they don't need to seal the entire filesystem. Installed using current EFI and iMac15,1 in about 15 minutes. Shutting down just shuts the machine down normally. I can see a ```CPU Halted``` message pass by as one of the latest message before it turns off and remains off.

What do you see on yours? It is pretty weird it turns back on cuz macOS just sends a power down message the same way Linux or Windows would do. It turning on again can have some cause like bios or ACPI but if you have the latest bios and use the default ACPI patches it should work.

My best guess would be that ```AC Recovery``` in the bios has been enabled or set to last instead of disabled. If you loaded bios defaults before making changes that should be off. Can't think of anything else that would cause the system to turn back on after sending a shutdown to it.

I'll apply the latest updates to it and see if that breaks anything. If it doesn't then I don't know what else I can try to reproduce. There were 2 macOS updates and one Safari update on my clean install of 10.14.6 -- shouldn't take too long to install those. I'll update here again once its done.

**Comment by zearp** [comment] 2021-08-15 14:31
For some reason the security update keeps failing at around 400mb downloaded and then says I'm not connected to the internet even though I am connected. I can't find 18G103 on the Apple website, but they have a newer security update ```18G9323``` released on the 5th of August: https://support.apple.com/kb/DL2078 -- I'll download it manually and install it.

![Update fails to download](https://user-images.githubusercontent.com/63272687/129481780-10ea72b5-0962-4f69-a695-deb68845fa9f.png)

**Comment by zearp** [comment] 2021-08-15 14:40
Got some nags to upgrade top Big Sur already. Luckily on Mojave we can disable all of those.

```
softwareupdate --ignore "macOS Catalina"
softwareupdate --ignore "macOS Big Sur"
```

Apple removed that option in Catalina for no reason other than to nag people into upgrading. Luckily we can use SMBIOS to block Big Sur or Monterey nags.

**Comment by zearp** [comment] 2021-08-15 14:46
Got some nags to upgrade to Big Sur already. Luckily on Mojave we can disable all of those.

```
softwareupdate --ignore "macOS Catalina"
softwareupdate --ignore "macOS Big Sur"
```

Apple removed that option in Catalina for no reason other than to nag people into upgrading. Luckily we can use SMBIOS to block Big Sur or Monterey nags when on Catalina.

**Comment by zearp** [comment] 2021-08-15 14:59
Update installed successfully and in true Apple fashion the update has now also disabled the ignore option in Mojave. Before installing the update it was hiding Big Sur properly and now it doesn't anymore.

![Mojave fully up-to-date](https://user-images.githubusercontent.com/63272687/129482618-c1c2c3c1-d0c6-4f8c-abda-d8bdc9bdcca6.png)

Ignoring Apple's push to upgrade, the system still turns itself off properly after installing all available updates. I have to conclude I can't reproduce it.

As sanity test can you confirm you can shutdown properly in Windows and Linux? I'm also curious if it happens when booted from the installer and shutting it down from there, does it happen there too? I would expect no operating system to be able to shut it down properly if it's something to do with the bios.

I am confident that my ACPI patches are not the cause of this, I've had Mojave installed before and also tried High Sierra at some point. I think I ran into usb issues on High Sierra but don't recall anymore, it been over a year that I tried older macOS. I'm only using Catalina and Monterey on my 7020s.

**Comment by MrSome1** [comment] 2021-08-15 15:44
Tell you the truth, it is the reason that I choose Mojave, new versions take much more time to install, and are pushed to update.
Yes, I' sure that it can poweroff normally in Windows and Linux, I used to use them as working system. As you told, the BIOS was updated to version A18, and set to default, where AC Recover is off. But the problem is still there, and there is a CPU Halted message before shuttimg down.
It's really strange, when boot from the USB to the installation interface, it powers off normaly. But boot from USB to Mojave, it shuts down then reboot. And more strange, I installed the Mojave about two month ago, and have used it for a few times, everything is OK. Then one day two weeks before, the shutting down suddenly breaks, but I have made no changes to anything.
Well, it is so kind of you to take so much time on this, don't bother, it doesn't matter at all. I am fresh for Hackintosh, and the key point is that, I don't konw how to catch the error message, so can not debug at all.
It is midnight at China, time for bed. Really nice to talk to you.
By the way, have a nice day.



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 15, 2021 22:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zearp/OptiHack] Poweroff but reboot then (#62)




 
Update installed successfully and in true Apple fashion the update has now also disabled the ignore option in Mojave. Before installing the update it was hiding Big Sur properly and now it doesn't anymore.
 

 
Ignoring Apple's push to upgrade, the system still turns itself off properly after installing all available updates. I have to conclude I can't reproduce it.
 
As sanity test can you confirm you can shutdown properly in Windows and Linux? I'm also curious if it happens when booted from the installer and shutting it down from there, does it happen there too? I would expect no operating system to be able to shut it down properly if it's something to do with the bios.
 
I am confident that my ACPI patches are not the cause of this, I've had Mojave installed before and also tried High Sierra at some point. I think I ran into usb issues on High Sierra but don't recall anymore, it been over a year that I tried older macOS. I'm only using Catalina and Monterey on my 7020s.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zearp** [comment] 2021-08-15 15:57
We have the same hardware, I didn't add any cards other than Airport cards for wifi/bt. I can't do much more than a clean install using the same EFI, same h/w and same bios settings. In theory we should have exactly the same configuration.

Let me know what it shows when shutting down, you may have to film it with a mobile phone as it can scroll really fast. On mine it shows the ```CPU halted``` message pretty much last before turning off and staying off. You didn't add any hardware right? Like pci-e device or usb thats always plugged in.

Yours turns off and then instantly turns back on? Does it fully turn off including the led on the power supply? Or does it remain on and just ends up rebooting? Do you see the ```CPU Halted``` message at all?

I don't think there's much else I can do then guess. You're the first to report an issue like this and I haven't run into this myself. I did have instant wake ups on one hacks but unrelated to this repo. And thats sleep related. Shutting down always worked. I can really only help when I can reproduce the issue.

**Closed as completed by zearp** 2021-08-15 15:57 UTC
Labels: can't reproduce

**Comment by MrSome1** [comment] 2021-08-16 02:16
There was a PCIe wifi card onece, but I have removed it to test the system.


I filmed how it shut down, but the mail server limited the file size, so I just saved one frame from the video. Oh my terrible phone, can you see the CPU Halted message at the last ？The power was totally cut off, as the power led was off, and seconds later it turned on again.


I have used hackintosh for a while, and now going to install a Windows or Linux to insure that the hardware is all right.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zearp/OptiHack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zearp/OptiHack] Poweroff but reboot then (#62)





 
We have the same hardware, I didn't add any cards other than Airport cards for wifi/bt. I can't do much more than a clean install using the same EFI, same h/w and same bios settings. In theory we should have exactly the same configuration.
 
Let me know what it shows when shutting down, you may have to film it with a mobile phone as it can scroll really fast. On mine it shows the CPU halted message pretty much last before turning off and staying off. You didn't add any hardware right? Like pci-e device or usb thats always plugged in.
 
Yours turns off and then instantly turns back on? Does it fully turn off including the led on the power supply? Or does it remain on and just ends up rebooting? Do you see the CPU Halted message at all?
 
I don't think there's much else I can do then guess. You're the first to report an issue like this and I haven't run into this myself. I did have instant wake ups on one hacks but unrelated to this repo. And thats sleep related. Shutting down always worked. I can really only help when I can reproduce the issue.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrSome1** [comment] 2021-12-29 10:14
Hi, there
&nbsp; Do you remember me, the guy who sufferd from a ghostly reboot after shutting down a few month ago?
&nbsp; The problem has been found, I guess, and you may be curious about this, so I'm here to tell you.
&nbsp; A few weeks ago when I powered up the PC, and it just failed, and a little lines on the black screen said that there was something wrong with the memory. After a while of struggling, I found that poor memory bank, and just removed it, so&nbsp; booted into desktop successfully. And since then, the PC never ghostly reboot again, until now for about 6 weeks.
&nbsp; I was surprised about this, what about you？



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 15, 2021 23:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zearp/OptiHack] Poweroff but reboot then (#62)




 
We have the same hardware, I didn't add any cards other than Airport cards for wifi/bt. I can't do much more than a clean install using the same EFI, same h/w and same bios settings. In theory we should have exactly the same configuration.
 
Let me know what it shows when shutting down, you may have to film it with a mobile phone as it can scroll really fast. On mine it shows the CPU halted message pretty much last before turning off and staying off. You didn't add any hardware right? Like pci-e device or usb thats always plugged in.
 
Yours turns off and then instantly turns back on? Does it fully turn off including the led on the power supply? Or does it remain on and just ends up rebooting? Do you see the CPU Halted message at all?
 
I don't think there's much else I can do then guess. You're the first to report an issue like this and I haven't run into this myself. I did have instant wake ups on one hacks but unrelated to this repo. And thats sleep related. Shutting down always worked. I can really only help when I can reproduce the issue.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zearp** [comment] 2021-12-29 12:28
Wow, thats is good information to know. Weird the computer didn't notify you about the RAM before. I guess it needs to fail the short self test before it notifies you but the RAM might have been faulty for a while. I will remember to do a full memory test when I run into weird rebooting issues. Thank you for sharing!

**Comment by MrSome1** [comment] 2021-12-30 02:21
Nice to hear from you.


Actually, the RAM is not broken down totally, the PC could still boot to desktop with it after a few tries. And I run the diagnost in the BIOS for a full RAM test, when it could boot, but there is no problem found, this was the weird point.


Since there were 4 x 4G RAM on my board, all Kingston by the way, so there were some unusual compatibility things or so. What I'm trying to say is that, if you happen to suffer from some strange issues, not only for Hackintosh, just keep one RAM on the board and keep going maybe a good idea.


Have a nice day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zearp/OptiHack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zearp/OptiHack] Poweroff but reboot then (#62)





 
Wow, thats is good information to know. Weird the computer didn't notify you about the RAM before. I guess it needs to fail the short self test before it notifies you but the RAM might have been faulty for a while. I will remember to do a full memory test when I run into weird rebooting issues. Thank you for sharing!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
