### ISSUE TITLE
Low resolution after wake from sleep external graphic card dGPU

### ISSUE THREAD

**Issue by davidAlaBer** [zearp/OptiHack#47] opened 2021-06-27 21:40 UTC
Low resolution after wake from sleep external graphic card dGPU

My card is Radeon RX 570 but It seems happen with other cards.
Displayport out. Metal enabled. DRM not enabled. iGPU disabled.
It seems the system can't remember the right resolution after waking from sleep.

**Comment by zearp** [comment] 2021-06-27 22:11
Does it fixes the resolution if you re-plug the cable?

If it does you can try making an IOreg dump in the terminal before sleep, another one once its woken up with the wrong resolution and other one once the cable was plugged in again. Just run ```ioreg > ~/Desktop/ioreg-before-sleep.txt``` it will create the file you pipe the output of the command to. To compare use the ```diff``` command or an app if you want it visually pleasing. Those dumps might have some differences which could help. They can also be all the same but its always a good thing to check what exactly changes in your hardware between these states. If only to get clues on what's going on.

Another thing to try is temporarily disable the ```force-online``` option or add it if you have it removed. That option is very involved with what the screen does after waking up. It is needed on certain monitors that don't wake up properly. I'm pretty sure that option applies to everything WhateverGreen controls, not just the iGPU. But I could be wrong.

Not all monitors need it, I leave it enabled by default cuz it doesn't seem to cause issues. If you have removed the whole block from the config then you'll gonna have to add it back. You can use the config I posted earlier, it has the block and the platform-id is set for compute mode. If all well Hackintool should show VDADecoder as enabled and Metal Headless too.

Another option which you already tested is the BIOS setting for video card. Which didn't make any difference I recall.

Thats about as much as I can think of, other than using search engines to try and find people who have the same issue. At least sleep and wake works, just a matter of fixing the resolution once it wakes up. 

DRM depends on the card and boot options, there's a [chart](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md) I found that explains it pretty well. Including what to expect on Big Sur and newer. Catalina is best bet for DRM.

I wish we didn't have insane hike of GPU prices cuz I was looking for a 2nd hand cheap (older) card thats natively supported just so I can test dGPU stuff too. But I'm not gonna pay these crazy prices 😃

**Comment by zearp** [comment] 2021-06-27 22:17
Forgot to mention an IOreg dump before sleep and after waking would be interesting even if replugging the cable doesn't do anything. Something changes somewhere, hopefully the IOreg dumps can uncover it.

**Comment by davidAlaBer** [comment] 2021-06-29 13:28
Hi!
A little time to test a few things
Does it fixes the resolution if you re-plug the cable? > No
force-online > No changes
DRM is not a problem
VDA Decoder > Decoder Failed (Hackintool)
<img width="568" alt="image" src="https://user-images.githubusercontent.com/34654112/123805701-96dfd680-d8ee-11eb-8c1b-0dbc0084a3ca.png">

**Comment by zearp** [comment] 2021-06-29 13:55
I think its best to fix this step by step, getting iGPU to work in compute mode is what I do first.

If you remove the whole block again does it fix VDADecoder and Metal Headless? 

Once thats correct move to sleep, make the IOreg dumps before and after sleep, clear all logs before sleep (or other tests), then put it to sleep and wake it up and check all the logs for sleep/wake related entries and see if anything useful is there.

Clearing all the logs is an important step cuz macOS can create sa lot of log entries pretty fast. Getting a clean slate makes it a lot easier to dig tonight lots of logs but it wil still be a tedious task. Please refer to the log sections on the repo. I wrote some general tips and tricks to read logs and clear logs including checking for sleep/wake events. Though you should also check other logs files in Console app and not just the system logs.

DRM works? According to the chart DRM is pretty useless in anything passed Catalina unless you don't have iGPU/disabled it. I'm asking for DRM things so this can also help others setup their dGPU properly. I would like to sort out all the dGPU stuff but like I said before the costs of buying one is too steep. I'd also need to buy at least two; AMD + Nvidia. Without me owning any of those cards it's very hard for me to help out. It will also take a lot more time. I hope prices normalise but I'm not counting on it for the foreseeable future.

Either way, try getting the iGPU to work in compute mode properly first, then focus on sleep. We need the dGPU + iGPU to be setup properly before moving on. If you can't get it in compute mode then it's best to disable the iGPU all together. This would be a good test to see if the iGPU has anything to do with the resolution breaking on wake. Once its disabled and it still happens then we know iGPU is not the cause.

To disable the iGPU you will need to edit or add if removed, the iGPU PCI block again in DeviceProperties. The only fields to add to disable it are the following:

- name, data field with as data 23646973706C6179
- IOName, string field, with as data #display
- class-code, data field, with as data FFFFFFFF

![config-gpu 65a08c27](https://user-images.githubusercontent.com/63272687/123809567-00151900-d8f2-11eb-9765-9bf2bc45ed93.png)

Lots of things to try and test, take it slow and do things one by and and step by step and you should be fine. I hope you can get compute mode to work cuz it will improve performance. If you can't make it work disable the iGPU and move on to sleep.

**Comment by davidAlaBer** [comment] 2021-06-29 14:13
Removing the whole block again does it fix VDADecoder and Metal Headless > NO

**Comment by zearp** [comment] 2021-06-29 14:20
What brand is your RX550?

It's very weird you can't get compute to work either with the correct headless platform-id and also not when removing the whole block. 

Have you had compute mode work in Big Sur or Catalina? I realise we're doing all this for a beta version of macOS. Not the best platform for these kind of tests cuz some things might simply be caused by the beta/bugs.

I checked prices and the cheapest low-profile RX550 or something else in that series I can find is around 100 euro already. More than I paid for my 7020s lol. I can find cheap GT7x0 Nvidia cards but they're not worth anything imho.

**Comment by davidAlaBer** [comment] 2021-06-29 14:32
Not RX550 is RX570 (ASUS)

**Comment by davidAlaBer** [comment] 2021-06-29 15:09
I tried with a backup Catalina disk and doesn't change anything. Thanks for you time. I googleed the issue and I saw other people with thw same issue. They talked about an out dummy fir iGPU even a physical end for the video out. It seems Dell doesnt deactivate iGpu even when we choose it in Bios. I will look for it.
Maybe I can leave without 'Sleep' fot the moment.

**Comment by zearp** [comment] 2021-06-29 16:05
You tried all the things I mentioned? Did you compare IOreg dumps and such too? What happened when you disabled the iGPU in the config? I've asked for a lot, I know and you can take your time and do the testing in Big Sur or Catalina when possible/time allows but I do need more information than what you're giving now in order to to do anything really. I've spend a lot of time writing and trying to make things as clear as possible and only ask things I would need to see or know about.

I can't help with getting sleep to work with the rom option set to disabled. I've tried that ages ago on several Dell models and it never worked. It is pretty much required for sleep to work. Maybe if you know ACPI inside out you can fix it with patches but I wasn't even able to figure out what exactly the rom option does/changes. It's a mystery. I am curious as to your logs though, what sleep/wake events are there. Any warnings or errors?

If we knew what the rom did we can maybe replicate it in ACPI or somewhere else and disable the option in the BIOS so sleep can work and the resolution thing will be gone. But I wasn't able to find anything on it other than generic info. We need in-depth technical specs about what it does. Maybe if someone works or knows someone at Dell they can provide the information but it might be "secret" to some extend.

**Comment by davidAlaBer** [comment] 2021-06-29 17:14
I am still learning a lot from Opencore and YOU!
I want you to take a look at [this thread](https://www.tonymacx86.com/threads/dell-optiplex-9020-sff-catalina-wake-up-screen-flickering.300995/page-2), because is the same error I have and probably you can take advantage of it for resolving this issue.

I know without the hw it's very difficult to test...
Thanks!

**Comment by zearp** [comment] 2021-06-29 18:20
The "patch" posted there is not a patch you can apply, it's not in a patch format but he poster says it's a patch. Confusing. 

It should have if statements and search/replace things. Patching it. Maybe they pasted into the DSDT... Or maybe they meant applying some of the builtin generic patches for wake-up/shutdown in MaciASL but there's a whole list of those in there and they didn't specify which. So I really don't know what to make of it and I'm not going to dig trough hundreds of lines of ACPI code to find out.  

They patch the complete DSDT like we used to do with Clover. With OpenCore thats exactly what don't do anymore. We only patch what is needed. While it's possible to create separate SSDT patches for this stuff I don't think any of the things in that thread apply here.

There is also a lot of ACPI patching going on in that EFI. It's not setup according to the Dortania guide or OpenCore's recommendations. Patching the whole DSDT is for Clover installs really anreven there it's better to only patch what is needed.

Have you tried booting with that EFI? That would be the quickest way to see if it actually fixes anything or not.

**Comment by zearp** [comment] 2021-06-29 18:22
The "patch" posted there is not a patch you can apply, it's not in a patch format but the poster says it's a patch. Confusing.

It should have if statements and search/replace things. Patching it. Maybe they pasted into the DSDT... Or maybe they meant applying some of the builtin generic patches for wake-up/shutdown in MaciASL but there's a whole list of those in there and they didn't specify which. So I really don't know what to make of it and I'm not going to dig trough hundreds of lines of ACPI code to find out.

They patch the complete DSDT like we used to do with Clover. With OpenCore thats exactly what don't do anymore. We only patch what is needed. With precision SSDT patches. While it's possible to create separate SSDT patches for this stuff I don't think any of the things in that thread apply here.

There is also **_a lot_** of ACPI patching going on in that EFI. It's not setup according to the Dortania guide or OpenCore's recommendations. Patching the whole DSDT is for Clover installs really and even there it's better to only patch what is needed.

Have you tried booting with that EFI? That would be the quickest way to see if it actually fixes anything or not.

**Comment by davidAlaBer** [comment] 2021-06-29 18:34
Ok. I understand. I am not going to change actual EFI. I have enough! :) :)

Thanks!

**Comment by zearp** [comment] 2021-06-29 18:35
Reading the other posts in that thread it suggests that setting primary output to dGPU instead of auto breaks the iGPU and the bIOS doesn't properly initialise it. They said it even breaks  things in Windows.

So my guess that in order for the iGPU to function in compute mode is that we must select auto. This could result in no display output if you have nothing connected to the iGPU DisplayPorts. But unlikely cuz Dell can detect when turning it on/rebooting if something is connected or not (hence auto) so should show boot-up/BIOS etc on the correct screen. If not it should still show display once macOS is done booting and loading the login screen.

The setting only controls which is primary so if you then set the platform-id to 04001204 or have the block removed in theory compute mode should work. It likely won't work when the BIOS is to use the AMD card as primary display.

You can also try my earlier suggestion and disable the iGPU in the config using the fields I posted and then set the AMD card to primary in the BIOS. In that configuration macOS shouldn't see anything but your dGPU.

Testing an EFI would just take a rename of the current one to EFI.bak and place the one to test in there and reboot to see what it does. But that's up to you.

**Comment by zearp** [comment] 2021-06-29 18:36
Reading the other posts in that thread it suggests that setting primary output to dGPU instead of auto breaks the iGPU and the BIOS doesn't properly initialise it. They said it even breaks things in Windows.

So my guess that in order for the iGPU to function in compute mode is that we must select auto. This could result in no display output if you have nothing connected to the iGPU DisplayPorts. But unlikely cuz Dell can detect when turning it on/rebooting if something is connected or not (hence auto) so should show boot-up/BIOS etc on the correct screen. If not it should still show display once macOS is done booting and loading the login screen.

The setting only controls which is primary so if you then set the platform-id to 04001204 or have the block removed in theory compute mode should work. It likely won't work when the BIOS is to use the AMD card as primary display.

You can also try my earlier suggestion and disable the iGPU in the config using the fields I posted and then set the AMD card to primary in the BIOS. In that configuration macOS shouldn't see anything but your dGPU.

Testing an EFI would just take a rename of the current one to EFI.bak and place the one to test in there and reboot to see what it does. But that's up to you.

**Comment by zearp** [comment] 2021-07-11 10:48
Any updates?

**Comment by davidAlaBer** [comment] 2021-07-11 10:55
No update. No time unfortunately and I need to learn how to debug it as you said. Summer project for me :)

I am working daily with Monterrey 9020 mt with dGPU RX570. It works fine!

Enviado desde mi iPhone

**Comment by zearp** [comment] 2021-07-11 11:02
I’ll close this Issue for now. You can open a new one when you have time.

**Closed by zearp** 2021-07-11 11:02 UTC
Labels: question

**Comment by zearp** [comment] 2021-08-12 14:58
Keeps opening issues and doesn't have time to sort it out, wants others do it for him. GTFO.
