### ISSUE TITLE
Mouse Freezes every 2 to 3 seconds

### ISSUE THREAD

**Issue by BrunoGM** [zearp/OptiHack#40] opened 2021-03-14 16:51 UTC
This will happen sometimes, somedays the hack works perfectly but somedays the mouse(or actually usb devices like the keyboard too) freezes for a second once every 2 to 3 seconds, needing a reboot to comeback to normal.

**Comment by BrunoGM** [comment] 2021-03-14 16:52
Ps: It was tested with more than 1 usb mouse

**Comment by zearp** [comment] 2021-03-15 03:39
I’ve not experienced this myself. Using usb wired and wirelessly pretty much every day on my Dells. What makes you think it’s due to the EFI? Nothing major has changed in a long time so I wouldn’t have a clue what would cause it.

Maybe another device is causing interference? If I put a usb disk in the usb slot right above the wireless usb dongle the connection gets bad and causes issues. It happens with usb sometimes.

Best I can suggest is to try different ports or as test an extension lead and see if it helps. Ones on the back are best as they’re not extended by cables and connect straight to the motherboard.

**Comment by BrunoGM** [comment] 2021-03-16 23:54
I have used your EFI with another non Dell Haswell system too and it had the same "bug", thats why i thought it could be the EFI. I m using some things from that build, like the monitor and usb bluetooth and other peripherals, since you don't have the same bug yourself it can be one of those indeed. Thanks for the answer.

**Comment by zearp** [comment] 2021-03-17 01:51
No problem, I hope you can narrow down what causes it. I have a few of these 7020s and have no issues with usb other than the expected interference. Are you using wireless or wired? If it's wireless it would be interesting to try with a wired mouse and see if it happens there too.

Some wireless usb and most bluetooth devices will act strangely if you use 2.4 ghz wireless. I can instantly notice when my hack has connected to 2.4 instead of 5 ghz. The mouse will jump between normal and very slow and laggy. If possible use 5ghz if not try to change channels on your router.

Good luck!

**Comment by BrunoGM** [comment] 2021-03-17 02:19
Yes, they are all wireless and bluetooth and i m using a bcm94360cs2 wifi pcie card. 

The problem happens very sporadically but when it happens it has a very obvious lag every 2 seconds pattern that wont go away till I reboot, thats why it looks to be more system related. I will be trying out another usb bluetooth adapter, do you recomend any cheap ones? I bought a 5.0 one to test this but it wasn't mac compatible like the 4.0 i have right now.

**Comment by zearp** [comment] 2021-03-17 05:38
I meant your wireless network signal. If you use 2.4ghz it will interfere with bluetooth and wireless usb dongles which uses the same band.

I’m a bit confused as to how your mouse is connected now. Is it bluetooth or usb? Cuz with bluetooth you may need to disable ASPM on some cards/system combos. Leaving it in can cause issues when it does power management stuff every now and then. 

If it happens note the time and check your logs files for anything bluetooth or usb related.

If it’s wireless usb try using a wired usb mouse and if it still happens it’s a usb issue. If it doesn’t it’s most likely interference. 

Does everything work fine in Linux or Windows?

You’ll gonna have to troubleshoot and exclude potential causes to narrow it down. I can’t really do much more.

**Comment by BrunoGM** [comment] 2021-03-20 00:55
The bug happens with the keyboard too, which is wired. I'm sure it's an USB related problem.

Since other people and you don't have the problem it must be something that is connected to my USBS, or.... my monitor? I didn't notice this problem happening with windows in the few days using it, seems to happen only in Mac.

I disabled ASPM as you suggested, it didn't solve the problem as it is a usb problem indeed, but I ll leave it disabled. 

If I get an answer I ll comment here, thanks for the help anyways.

**Comment by zearp** [comment] 2021-03-20 14:00
Your best bet when things are vague like this is to keep an eye on the logs. Like I said earlier, as soon as it happens note the system time and then dive into the logs around that time and look for usb events.

If you can also try other wired/wireless keyboards and mice. Just to exclude the keyboard/mouse being the issue. But I don';t think that is it. Did you change anything from the default config?

Did you apply the bios usb settings? Does it happen with any usb device? Like if you have an audio interface or something else does it disconnect or have weird issues?

When testing disconnect any usb device that isn't strictly necessary. The only way to get to the root cause is to exclude other causes. It can be boring and tedious but troubleshooting by excluding things is one the best ways to find a cause and then hopefully fix it.

Another thing that comes to mind, are you using ports on the font or the back? Test it in the back prots cuz they're connected to the motherboard directly and if they work fine then the cable connecting the front ports might not be fitted properly or has dirty contacts or something. Try reseating the cable(s) if the back ports work ok.

Seemingly random events are the worst so I feel your pain. When I had my first 7020 it came with an i3 and I've spend way too many hours trying to fix the graphical glitches only to find it was simply impossible since the i3 has a HD4400 in it that was never officially supported by macOS so will always be buggy. It pretty annoying cuz everything worked fine except for those random moments when it didn't.

I'll close this issue as it doesn't seem to be caused by the EFI but something else. But do keep me posted. I'm curious if your logs have any usb related failures or errors in it.

**Closed as completed by zearp** 2021-03-20 14:00 UTC
Labels: can't reproduce
