### ISSUE TITLE
Hardware advice

### ISSUE THREAD

**Issue by davidAlaBer** [zearp/OptiHack#23] opened 2020-10-12 21:22 UTC
Hi!
I hope you are well. Today I turned on my OptiHack and I got a black screen and no beep (I was very happy with it and fully functional)  and 'no display video' in the monitor. After checking cables an video outputs (dGPU and iGPU)  I thought maybe the cmos battery was drained (I have had clock time issues in windows and Bios), I replaced it and nothing changes. Reset cmos and check ram and cpu and other tests I found googling.
Many test after I guess the motherboard is broken.

1. Should I buy a second hand in aliexpress?
2. Should I check any other thing?
3. My configuration (dGPU+600wPSU) is a hard load for the motherboard?

I will find very useful your opinion, not a hardware expert here.

**Comment by zearp** [comment] 2020-10-12 21:57
Sorry to hear about that.

I'm not sure if it's worth buying a new motherboard, unless it's really cheap. I've seen i3 models without ram go for less than $50. 

Before spending any money it would be best to know more about the issue and maybe find a cause. You don't want to order a new board to find out the cpu also stopped working. It's possible that the board could've been overloaded by the dGPU power draw but not very likely as it would protect itself from such things on a few levels.

When you turn it on is it completely dead or do the fans spin up?

Try the original power supply and not use the dGPU for the time being

If you remove the ram sticks does it beep? Sometimes just removing and putting it back helps too.

Do you have a wired keyboard connected or one you can plug in? If so, connect it and turn on the computer and see if you can enable numlock or capslock.

Try booting the machine without any disks connected and just ram. Also try the full cmos/nvram reset as described [here](https://github.com/zearp/OptiHack#resetting-uefi-changes). I had to do it the other day after playing around with some vars in UEFI shell. I just got a black screen when it turned on and strangely my power led was very dim, from a distance it looked turned off.

If none of that works do one last thing; check the service tag on the Dell website. Some of my 7020's still have NDB warranty till next year. They usually ship with 3 or 5 years of warranty. YMMV.

You'd have to go trough the hassle of transferring ownership, which Dell supports for (eBay/2nd hand) purchases but Dell also likes to know details of the previous owner even though sellers won't be allowed to share those details with you due to privacy rules everywhere. If you keep your foot down they will eventually transfer it to you and then you can have tech swap the board in your home within a few days, or have them ship a new board if you prefer that. It will cost you an email every so many days. I've always gotten the warranty transferred, sometimes it goes fast sometimes it takes many weeks of emailing and escalating the case a few times haha.

**Comment by davidAlameda** [comment] 2020-10-12 23:47
Thanks for your quick response.
Some facts:

Optiplex i5-4570

When you turn it on is it completely dead or do the fans spin up?
> Fans spin up

Try the original power supply and not use the dGPU for the time being
>Done

If you remove the ram sticks does it beep? Sometimes just removing and putting it back helps too.

>1 - 3 - 2

Do you have a wired keyboard connected or one you can plug in? If so, connect it and turn on the computer and see if you can enable numlock or capslock.

>no light in caps lock. 

Try booting the machine without any disks connected and just ram.
>nothing

Also try the full cmos/nvram reset as described here.
>No video or beep. Nothing new. Only static noise that ends when i press the ON/Off button

If none of that works do one last thing; check the service tag on the Dell website. 
>Warranty ended April 2018 :(

What can be the cause?  Do you mean both the Cpu and the motherboard can be broken?

Thanks in advance

**Comment by zearp** [comment] 2020-10-13 02:45
You got the correct beeps relating to no ram present. That's good news. Means the cpu and board most likely aren't dead!

First try one ram module in all slots and see if you get a picture in one of them, then try with the other modules one by one. That way you can test them and also test the slots and by removing and reseating them clean the contact a bit too. You will know the ram stick works if it doesn't beep an hopefully output picture.

I assume you're using the iGPU and DisplayPort and also reset the BIOS so it will default back to auto for the graphics and not try to output somewhere with nothing attached.

Just know that beeping means your cpu and board and most likely still fine. Could be a ram module has died or needed reseating.

Good luck!

**Comment by zearp** [comment] 2020-10-13 02:47
You got the correct beeps relating to no ram present. That's good news. Means the cpu and board most likely aren't dead!

First try one ram module in all slots and see if you get a picture in one of them, then try with the other modules; one by one. That way you can test them and also test the slots and by removing and reseating them clean the contacts a bit too. You will know the ram stick works if it doesn't beep and hopefully outputs some video signals.

I assume you're using the iGPU and DisplayPort and also reset the BIOS so it will default back to auto for the graphics and not try to output somewhere with nothing attached.

Just know that beeping means your cpu and board and most likely still fine. Could be a ram module has died or needed reseating.

Good luck!

**Comment by davidAlameda** [comment] 2020-10-13 08:57
No beeps after ram modules test as you said. I assume they are good.
No luck with the picture. 
The led is normal, not blinking, no amber.
Crazy.

**Comment by zearp** [comment] 2020-10-13 13:20
You tested every module on its own? If so thats good, then all your ram should be ok.

It is probably something unexpected now, as everything appears to work fine. 

Do you have any other computers? IF so you could put the disk back in and boot to macOS again, watch the disk led. Check on your router what DHCP leases are active to find the IP of it and try to ping it. You can also remote desktop in if you had that set up.

I'm pretty certain everything works except video output. Which could then be a few things; cable, port, somehow BIOS but unlikely and also unlikely the iGPU just stopped working and the rest of CPU is fine, impossible I'd argue. Try booting with the dGPU connected to the screen with the original power supply.

Another thing to try is of course another cable and another screen (a tv is fine too). We're really just excluding causes and testing things to limit the number of problem makers.

I really hope you got some other computers there so you can do the ping/network testing. Let me know if something is unclear. I'm confident this issue can be solved, it doesn't appear to be something super bad as your tests show a lot of h/w still works fine in there.

**Comment by zearp** [comment] 2020-10-13 14:17
The thing is that in order to beep several things have to work, including the cpu and motherboard. And it does detect it when you remove the ram. The fans spin normally and don't go to max speed (which they do if something is wrong in BIOS). 

The tricky thing is that we can't really verify if the disk actually tries to load macOS or maybe there's a BIOS message saying press F1 to continue due to fan error or something small. I take it you didn't enable vPro/AMT, not many do but that would be another way to get access and see what's going on. On most Optiplex the AMT section is incomplete and needs updating. But thats besides the point.

I'm thinking of something you could do to make sure you're really booting an OS. The best thing I can think of is to make a Linux installer that boots into a login/demo screen without any user intervention. I think the popOS and Ubuntu ones do that. They will try to fetch an IP on your network and should show up in the DHCP lease list on your router if it worked.

The thing with no video output is that it's tricky to prevent these small from messing up the testing. Like one of those warnings Dells like to throw out if you touched the fan while it was on and open. Pressing F1 for a while after turning it on might help. And boot without any disks connected, if all is well the BIOS will try to boot form the usb stick.

One thing that is weird too is that you don't get any picture using the onboard outputs or the output in the dGPU. I would assume that if the onboard outputs are broken it would still work on the dGPU or the other way around. And since you reset the BIOS several times the chance that the video card selection option is set to external is also very slim.

Buying a new motherboard might not help since we didn't really find a cause yet. Of course it is also possible that he board did get overloaded and blew out something somewhere that requires board level repair and causes this issue. That would be an unlikely but valid explanation. If some cap somewhere got blown everything might appear fine but the actual h/w paths the video signal has to take is broken somewhere along the line. Fixing that would require a few hours, a multi meter and a tame Louis Rossmann.

You've pretty much tired everything and even out the board out and just connected ram and power and still nothing. Very weird indeed. If the BIOS/CMOS was corrupted the power led would blink and the fans would spin at max rpm all the time. the only error messages you can trigger is by removing ram, so the self tests pass everything. Thinking about that leads me to think about the F1 prompt, it may just be waiting for F1 to be pressed to continue booting, even without video signals. Would be nice to test that out and since you got remove desktop enabled you will spot it on your network it actually booted macOS.

**Comment by davidAlameda** [comment] 2020-10-14 20:46
Thanks for your suggestions. No way to unlock this motherboard, keyboard is not working, no F1 or led in the keyboard. No video signal. No linux usb boot.... I have ordered a second hand motherboard for 50€, then I hope to boot from the original ssd windows hd and I will follow your guide again. I trust CPU is ok. I am learning a lot!
Keep you informed!

**Comment by GCPDetective** [comment] 2020-10-15 02:22
If the fans spin up, then try turning the tower on and letting it sit there for a few minutes. If still nothing unplug the tower and then press the power button for a few seconds to drain any flea power. Then plug the tower back in and turn it on. if its still black just wait a few minutes again and then check if you see any video signal. I have a similar issue that pops up once in a blue moon with my Optiplex 9020 MT lol.

Unrelated: SUP ZEARP XD! I installed Big Sur on my OptiHack the other day and seems to be running stable. About to try and upgrade to Developer Beta 10 in about an hour.

**Comment by davidAlameda** [comment] 2020-10-15 15:10
Thanks but no luck.
My son (7) confessed he tried to boot to windows pressing esc and presssing ON button several times, maybe too much electrical shots, or may be he screwed up something through the oc picker.
I guess bios it is bricked or motherboard failed. All test are done in my opinion.
[IMG_2270.MOV.zip](https://github.com/zearp/OptiHack/files/5385851/IMG_2270.MOV.zip)

@GCPDetective, one question for you: is there any led on the board of your 9020 mt motherboard when the computer is on?

**Comment by GCPDetective** [comment] 2020-10-15 22:33
No, my one doesn’t have a light on the motherboard (Don’t mind the rats nest, got lazy with cable management after taking the tower apart a few times LOL).

![8680AEA0-D4A1-4FB4-8421-B42E19AFC440](https://user-images.githubusercontent.com/56003049/96192766-ba0b5700-0f14-11eb-8caa-624dd6bc8968.jpeg)

**Comment by zearp** [comment] 2020-10-16 02:54
@davidAlaBer Sorry for the long reply haha. It happens sometimes! Long story short; the new board will probably fix everything! Some more theorising below.

I'm pretty certain messing with power buttons or things like that would not cause this. These machines are build to a much higher standard than average consumer pc's. From the materials used to the ratings of buttons (millions of presses), custom made boards and an efficient power supply. They can handle some abuse and misuse. I know from experience that an office full of people totally not interested or even care about how things work, can break things faster and to a worse degree than a curious child lol.

If the BIOS would be toast the fans go max rpm as fail safe and things such a beep error codes won't work. Usually when the you can get error codes to show or sound it means the board + BIOS + CPU are fine. It's the BIOS thats produces those error codes which require both some logic to work and the board traces to be intact to send signals around and to the speaker. While not outputting any display the computer does turn on and then the BIOS fails to see any memory and sends out the error codes. All this doesn't solve the issue though but interesting from a troubleshooting side.

- BIOS functions due to error codes being sent and fans not going max speed
- RAM works as tested with the beeps
- CPU most likely works too

Since above all work it's unlikely that there's a big hardware failure A small hardware failure like a blown trace on the board is also unlikely but a small chance due to the high capacity power supply. I don't know what the max power rating is of these boards but then still these boards won't take more power than they can handle. Rare but possible I guess.

From my experience those things would normally indicate the hardware is ok and something else is up. But it's hard to do these kind of things without seeing the hardware in person. It could be anything from a blown trace on the board to somehow the machine not finding a video output due to messed up firmware or confused BIOS. Not everybody has spare parts laying around or other computers to test parts in so at some point we get stuck excluding possible causes.

I think you get some money for it still, sell it for spares and repairs but do mention memory error codes worked when you tested it. Should at least bring in $25 for just the board for someone to learn with or just fix it or scavenge it for parts. There's some nice chips on the board. I'm curious if there's some way to get debug output over the serial port to see what's going on or just get another video out. Speaking of those, have you tried the VGA output? Not very likely but who knows. I'm also not certain if it's always a press F1 to continue message if fans failed or BIOS was reset etc etc... but it will print some warning before it boots. Everything might just work except video output. But tricky to test and it just costs a lot of time.

The cheapest and best option is to do what you did, get a new board. For me personally I would investigate it as it useful in my work too. But it's not worth spending hours on when the goal is to fix it.

(I'l close this issue now but please update when the board is up and running! I'm not sure if you now but Dell has pretty detailed guides for their business machines when it comes to assembly/disassembly. Just in case you need some reference.)

@GCPDetective Big Sur working well here too. The only consistent issue I ran into is my bluetooth keyboard not working after sleep, but my mouse is. I have to turn the keyboard off and on. Might be a macOS bug since I use an Apple card and keyboard. The GM should be soon and I hope it's fixed cuz I haven't been able to track it down and I also have bluetooth connectivity issues on my real Macs. But for some reason there it's the mouse that gets disconnected randomly. When running Catalina all is good so I blame Apple for now.

**Closed by zearp** 2020-10-16 02:54 UTC

**Comment by davidAlaBer** [comment] 2020-10-22 15:47
Hi again!
New Motherboard (second hand from China) and the system is working again!.
Well, this is my first broken/bricked/whatever motherboard ever!  :(  It has never happened with a Mac :)
My Ram and CPU seems ok.

I still wonder why it failed and if it is something I can do to prevent it. 
PSU works (should you test voltage?, It is new and 80plus Bronze 650W certified).

**Comment by zearp** [comment] 2020-10-22 16:24
I'm glad the new board works including RAM and CPU. Maybe your BIOS got corrupted somehow but it's so unlikely to just happen as those regions are protected unless the jumper is shorted or an official Dell BIOS update is installed. You could spend $10 on a BIOS programmer that can be clipped on the BIOS chips and dump the data in there then validate it. But it would still leave the option open for some chip or capacitor or something broken even if the data in BIOS chips is valid.

**Comment by mgrimace** [comment] 2020-10-28 00:49
On the topic of hardware - I just purchased the FENVI HB1200 network card and wifi worked out-of-the-box on my SFF Optiplex 7020 Hackintosh. What I'm not certain about is if it's also possible to get _bluetooth_ working specifically on the SFF model - as far as I understand Bluetooth needs an internal USB (which comes with the card) and the SFF version doesn't have one. Do you know if it is possible to get bluetooth working with this card?

**Comment by zearp** [comment] 2020-10-28 01:53
@mgrimace I used an internal to external usb cable and routed it out a backplate to a USB port on the back. It sounds janky but it's not too bad. I mapped that port as internal and it works great. I used an older video card backplate and reused the large port opening for the two antennas and the other one for the usb cable.

![T1Hc_7XfpcXXbQ0_wT_013203__73906_zoom](https://user-images.githubusercontent.com/63272687/97380785-116fd680-18c8-11eb-9187-b04c673010e9.jpg)

A cable like that. Be sure to get one long enough to reach from the back of the card to the outside. I barely use the usb 2 ports on the back so "losing" one for bluetooth isn't an issue. I use an Airport card and even the proxy hid mode works. That is I can enter the BIOS using my bluetooth keyboard. The Airport card "converts" any paired hid device as normal usb device when macOS isn't running. Even in Windows lol. I don't know if the Fence does that too, I would assume it does if it's a 1:1 clone.

I'll see if I can take some pics of my "janky" 7020.

**Comment by zearp** [comment] 2020-10-28 02:03
Here it is! The usb cable that came with my converter board is connected that to the cable I posted earlier. I'm a bit surprised it works cuz I use a pci -> m.2 converter card which houses a m.2 -> Apple pin converter which houses the Airport card. I even had to use some captan tape to secure it cuz there was no stand off hole that would align. But it works!

![IMG_0092](https://user-images.githubusercontent.com/63272687/97381519-8d1e5300-18c9-11eb-9893-5dba2ff86c5e.JPG)

**Comment by zearp** [comment] 2020-10-28 02:05
Here it is! The usb cable that came with my converter board is connected to the cable I posted earlier.

I'm a bit surprised it works cuz I use a pci -> m.2 converter card which houses an m.2 -> Apple pin converter which houses the Airport card. I even had to use some captan tape to secure it cuz there was no stand off hole that would align. But it works!

![IMG_0092](https://user-images.githubusercontent.com/63272687/97381941-76c4c700-18ca-11eb-9f3a-7542b2247813.JPG)

**Comment by mgrimace** [comment] 2020-10-29 00:39
Thanks so much for posting the info and the photo! I picked up a cheap cable adapter off Aliexpress which should arrive sometime in the next month or so lol. My goal is to see if I can route it through one of the holes in the unused bracket cover. That's interesting you hacked in an airport card and glad it works! FWIW if anyone else is looking the Fenvi-HB1200 fits perfectly (no modding other than the USB cable for the SFF) and it came with a half-height bracket which fits the 7020 SFF perfectly. I'll report back in with bluetooth but no changes necessary to get wifi working, truly out of the box.  I paid 20$ USD on Ebay, but I think I got lucky, I've been seeing them around 40$ on Aliexpress.

Re. USB - I have plenty of slots as well on the back so no issues there. With flipping an external USB to internal, is that just a matter of changing the designation in Hackintool (assuming the port-map is already done)? I.e., under USB and the 'connector' column change USB2-> internal and export the new kext, save into EFI/kexts? Or would it require re-doing the port-mapping from scratch? 

Thanks again, much appreciated. I wonder if it's worth adding a hardware/modding section to the guide?

**Comment by zearp** [comment] 2020-10-29 13:17
@mgrimace Setting a port to internal is as easy as looking up which port it is in Hackintool, like HS06 and then change the [integer](https://github.com/zearp/OptiHack/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L91) for that entry to 255. Save and reboot. You may need [some kexts](https://github.com/acidanthera/BrcmPatchRAM) for bluetooth but you'll find out soon enough. I needed them for my Dell DW1820A but not for the Airport ones I've tried.

As for wifi I would recommend setting your region to #a. This allows for much faster speeds as it "unlocks" 80mhz channels in all regions amongst some other things. I've tried a few regions and couldn't get 80mhz channel width to work. The speed difference is quite big. You'll need to add [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup) and add ```brcmfx-country=#a``` as boot flag.

I've looked into the Fenvi and you got a really good deal. I wasn't able to find anything priced reasonable so I went with my conversion sandwich haha. I paid about $8 for the pci card and $3 for the m.2 to Apple board and another $15 for the Airport module. I got the BCM94360CS2 which isn't the fastest ac card but it was priced well for one that didn't have to come from China. I've gotten some very cheap BCM943224PCIEBT2 cards but they only do 300mbit on 5ghz, so might not be suitable in all builds and takes some tinkering to make it work in Big Sur (for now). But they very cheap for real Apple cards. Seen them as low as $5 with free postage on sale on Ali.

**Comment by mgrimace** [comment] 2020-10-29 23:27
> To check your channel width hold down alt while clicking on the wifi icon:

Interesting, my channel by default says 44 (5Ghz, 80 Mhz), no changes made, no AirportBrcmFixup. I'm in Canada, it could be that it's unlocked by default based on my actual location. Thanks for the info re. where to find the integer to change - it looks like the cable will take a while to ship but once it does I now know what to do. Much appreciated!

**Comment by zearp** [comment] 2020-10-30 00:31
@mgrimace You'e welcome! 

I didn't try Canada of the ones I tried. Guess I had bad luck cuz I tried a bunch of countries lol. I'll leave it at #a for now, everything is stable. Sometimes my password wouldn't be accepted on 5ghz. Found out this was due to my router being set to auto channel. So depending on the channel it would or would not accept the password. macOS can be so fussy sometimes.

For bluetooth you may or may not need those kexts, I would try them anyways and check the firmware versions with and without them. Sometimes the kexts have newer firmwares or the other way around or the same. Not that it really matters just one of those things that are good to know, in case you run into weirdness you can try different bluetooth firmware versions. I do wonder if the Fenvi cuts power to the chips when sleeping. On these converter cards it does so I can't wake it up from sleep with bluetooth devices. It's the only thing that doesn't work like on a real Mac.

(Funnily enough with a $2 bluetooth dongle I can wake it up from sleep using bluetooth devices...)

**Comment by mgrimace** [comment] 2020-12-01 20:22
Ok, so my cable from AliExpress finally came to connect my bluetooth to the Fenvi wifi module (FV-HB1200)!

**Installation** - well I broke the little plastic tab cover on the port of the USB card itself (where the tiny USB connecter connects). The pins are fine, the top of the receiver plastic is very small and flimsy and I'm clumsy and didn't want to remove the card just to add the cable. I sort of bent it off as soon as I tried to plug it in. No problem though, it's in it's fine and holding (not wobbly or anything).

**routing the cable** - for now I just pulled off the second PCI cover and routed the USB cable externally through that slot. Since the slot cover is like a grating I think I'll just file out a larger hole to pass through the USB and recover it back up.

**Setting the port as internal** - the card connects to an external port, and I followed your advice to swap it to internal. I selected HS09, seemed mostly out of the way. If anyone else is doing the same, the process is to open up Hackintool and you'll see which USB port it's connected to. Then mount your EFI, right click on the USBports.kext click "show contents", find info.plist, open with ProperTree. Then find HS09 or whatever USB it's connected to and change the "0" integer to "255".

**Results** - unlock with Apple Watch is working, continuity+handoff seems to be working (app shows up on dock now, and I just copied the word "Testing" on my iPhone and pasted here on my Mac). No additional modifications/kexts needed, and seems to be functioning like Vanilla!

Thanks @zearp !

FYI the bluetooth module shows up as BRCM20702 Hub in Hackintool.

**Comment by zearp** [comment] 2020-12-02 15:06
@mgrimace Nice! Thanks for updating. Having native Bluetooth and wireless really finishes these builds I think. Mine has been ricinusolie for months and months. I had more issue with my MacBook than my Dells 🥲

**Comment by zearp** [comment] 2020-12-02 15:07
@mgrimace Nice! Thanks for updating. Having native Bluetooth and wireless re @mgrimace Nice! Thanks for updating. Having native Bluetooth and wireless really finishes these builds I think. Mine has been ricinusolie for months and months. I had more issue with my MacBook than my Dells 🥲 ally finishes these builds I think. Mine has been rock solid for months and months. I’ve had more issue with my MacBook than my Dells 🥲

**Comment by zearp** [comment] 2020-12-02 15:08
@mgrimace Nice! Thanks for updating. Having native bluetooth and wireless really finishes these builds I think. Mine has been rock solid for months and months. I’ve had more issue with my MacBook than my Dells 🥲
